# Site settings
title: From Premed to Programming
header-img: img/home-bg.png
email: alexgzhang92@gmail.com
copyright_name: AlexGZhang2014
description: > # this means to ignore newlines until "baseurl:"
  One day at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AlexGZhang2014
learn_profile: AlexGZhang2014
email_username: alexgzhang92@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
